### PR TITLE
Fix unbound variable BEAKERLIB_PROFILING

### PR DESCRIPTION
**Pull request by atodorov**
Otherwise causes failures for lorax tests:
https://github.com/cockpit-project/bots/pull/1627
https://github.com/weldr/lorax/pull/1112

### CODE REVIEW

**Review by hegerj — APPROVED** [review]

**Comment by sopos** [comment]
I would prefer it to be placed in the profiling.sh, somewhere before line 63 so it is nicely together with the rest of the related code.

**Comment by sopos** [comment]
@hegerj , what do you say to may change? If it is ok from your POV, let's squash and merge.

**Review by hegerj — APPROVED** [review]
It makes more sense to put it with the rest of profiling

**Comment by atodorov** [comment]
I am seeing this error in my downstream testing:
http://artifacts.osci.redhat.com/testing-farm/aeaf4338-d9c6-4e5c-bb51-9c1bd9114cc1/

Can we get a new RPM released ?

**Pull request merged**
