### PR TITLE
Fix for bz1234810 - wrong number of passed/failed tests

### PR DESCRIPTION
**Pull request by mnalband**
The purpose of deleting that part of file is because it actually doubled `((TotalPassed++))` and `((TotalPassed++))`. 

Actual result:
```
$ ./test.sh test_rlAssertLesser
 [ INFO ] Testing test_rlAssertLesser
 [ PASS ] 1 good logged for 'rlAssertLesser "comment" 1 999'
 [ PASS ] 0 bad logged for 'rlAssertLesser "comment" 1 999'
 [ PASS ] 1 good logged for 'rlAssertLesser "comment" -1 1'
 [ PASS ] 0 bad logged for 'rlAssertLesser "comment" -1 1'
 [ PASS ] 0 good logged for 'rlAssertLesser "comment" 1000 999'
 [ PASS ] 1 bad logged for 'rlAssertLesser "comment" 1000 999'
 [ PASS ] 0 good logged for 'rlAssertLesser "comment" 100 10'
 [ PASS ] 1 bad logged for 'rlAssertLesser "comment" 100 10'
 [ PASS ] running 'rlAssertLesser comment -2 -1' (all parameters) must succeed
 [ PASS ] running just 'rlAssertLesser ' (missing parameters) must not succeed
 [ PASS ] running just 'rlAssertLesser comment ' (missing parameters) must not succeed
 [ PASS ] running just 'rlAssertLesser comment -2 ' (missing parameters) must not succeed
 [ PASS ] Testing test_rlAssertLesser finished: 12 passed, 0 failed, 0 skipped

 [ PASS ] Total summary: 12 passed, 0 failed,  skipped
```

### CODE REVIEW

**Comment by sopos** [comment]
It looks like this patch removes too much, particularly the performance part and too less particularly in the SCOREFILE handling. It looks like we really do not need to generate the SCOREFILE at all. There fore I would just remove all the SCOREFILE handling (creation, filling, reading, and removing).

What's your opinion?

**Comment by mnalband** [comment]
@sopos I think it should be in that way, because keep `SCOREFILE` is useless.
So, I need just to clear `test.sh` from `SCOREFILE` (that left part in file)?
```
export SCOREFILE=$(mktemp) # no-reboot
printf "%i:%i:%i\n" $__INTERNAL_ASSERT_PASSED $__INTERNAL_ASSERT_FAILED $__INTERNAL_ASSERT_SKIPPED>> $SCOREFILE
```

**Comment by sopos** [comment]
Yes I would say so, also there is some 'rm' part.
And also return that part with TIMEFILE back.

**Comment by mnalband** [comment]
Added new commit [https://github.com/beakerlib/beakerlib/pull/9/commits/5e840df24fea389c9b265432e243944c60a71c11](url)

**Pull request merged**
