### PR TITLE
Enable integration testing with tmt

### PR DESCRIPTION
**Pull request by psss**
Let's enable a couple of integration tests with `tmt` to ensure everything works fine together.

### CODE REVIEW

**Comment by psss** [comment]
The new plan is disabled for `centos-7` so there only package installation tests should be performed. Let's see...

**Comment by psss** [comment]
> The new plan is disabled for `centos-7` so there only package installation tests should be performed. Let's see...

This did not work. As @thrix has explained to me, package installation testing is triggered by packit only when no fmf metadata are detected. Added a separate tests section instead.

**Comment by psss** [comment]
Now everything seems to be green. @sopos, what do you think?

**Comment by sopos** [comment]
Is it necessary to execute that many tests? Are all of them affected by beakerlib in different ways?

**Comment by psss** [comment]
Well, we don't have to. On the other hand, the whole set of `tier:1,2` tests takes about 10 minutes (for now). If you think it would be better to select just a few test-execution-only-related tests we can add `test: execute` to filter more. This gives about 7 tests. Does that seem to be a better approach?

**Comment by sopos** [comment]
> If you think it would be better to select just a few test-execution-only-related tests we can add `test: execute` to filter more. This gives about 7 tests. Does that seem to be a better approach?

I would say so, the other tests are unrelated from beakerlib POV and may produce some false failures.

**Comment by psss** [comment]
Ok, the plan updated accordingly.

**Comment by psss** [comment]
Everything green. Any other comments? Ready to merge?

**Comment by sopos** [comment]
@psss, thank you!

**Pull request merged**
