### PR TITLE
Enable colors on rxvt-unicode (aka urxvt)

### PR DESCRIPTION
**Pull request by AloisMahdal**
rxvt-unicode sets TERM to 'rxvt-unicode'.

### CODE REVIEW

**Comment by sopos** [comment]
Thanks for the fix. I'll merge it.
And yeah, the list is of terminals is definitely not complete. The idea was to gather terminals and their escape sequences on the go.
I'm not sure whether there is some list available around which we could use right away to speed the process up.

**Comment by AloisMahdal** [comment]
FTR, I just tested *konsole*, *terminator*, *xfce4-terminal* and *gnome-terminal* -- all of them use `xterm-256color`, which is already covered by beakerlib.  (I realized that I have a vague memory of reading somewhere that rxvt is the one that tends to be the "special snowflake".)

**Comment by sopos** [comment]
Ok, let's merge this one and we'll see what's next. :-)

**Comment by sopos** [comment]
One more thing. Wnat about other variants of rxvt? Shouldn't we use rxvt*, not just the unicode version?

**Comment by AloisMahdal** [comment]
You're right; I tested it with plan old rxvt and indeed it sets `rxvt`.  Thanks, I've updated the patch.

**Comment by AloisMahdal** [comment]
FTR; one more in Fedora is *rxvt-unicode-256color*, which sets `rxvt-unicode-256color`.  Then for each of *rxvt-unicode* and *rxvt-unicode-256color*, there are `-ml` (multi-language) versions, but they set the same TERM as the other ones.

*(- sound of /me wiping the sweat from my forehead -)*

**Pull request merged**
