### PR TITLE
added phases and asserts fingerprints

### PR DESCRIPTION
**Pull request by sopos**
each phase and assert saves its status into an array whi is then used
for pringerprint counting as first 7 letters of base64 of sha256sum
of the respective statues

### CODE REVIEW

**Comment by hegerj** [comment]
What are the status arrays and fingerprints for if I may ask?

**Comment by sopos** [comment]
Those arrays are just for the fingerprint construction.

The fingerprint is good for comparing e.g. old and new run to help to identify a regression even though the test fails on both.

I just wanted to ask for a review and a need for some documentation to agree on a proper place.

**Review by hegerj — APPROVED** [review]
LGTM

**Comment by hegerj** [comment]
> I just wanted to ask for a review and a need for some documentation to agree on a proper place.

I am not sure I understand what you mean by this. Wouldn't man pages be the proper place for documentation?

**Pull request merged**
