### PR TITLE
fix: tmt integration

### PR DESCRIPTION
**Pull request by LecrisUT**
- update tmt url reference
- bump test target to epel-9
- cleanup packit.yaml file
- fix test filtering
- fix tmt plan packages

Depends on https://github.com/teemtee/tmt/pull/2731

### CODE REVIEW

**Comment by psss** [comment]
All tests green \o/

**Comment by LecrisUT** [comment]
:+1: I think on this side I just need to drop fbd2d6e6f7cfdb322df2f6aeb6c22d8659bb8805? `ref: fedora` is still intended?

**Comment by psss** [comment]
> 👍 I think on this side I just need to drop [fbd2d6e](https://github.com/beakerlib/beakerlib/commit/fbd2d6e6f7cfdb322df2f6aeb6c22d8659bb8805) after everything is merged?

Yes, once the `tmt` part is merged.

> `ref: fedora` is still intended?

Good question. For the basic functionality tests should be ok to drop it as well. On the other hand we're testing against the released `tmt` package in Fedora, so some minor incompatibilities might appear. @lukaszachy, what do you think?

**Comment by lukaszachy** [comment]
I'd prefer to test against main branch, it has to be stable wrt. beakerlib.

In the future we might remove fedora branch and use distgit/srpm to get test sources  instead.

This fedora branch is just a workaround.

**Comment by LecrisUT** [comment]
@sopos do you want to cherry-pick 530caf62b206c268a37414b4ca41bd795de19c89 onto master? Probably a rebase error sneaked in bc52b426205949eae413136b38d719c333f91e9a

**Comment by sopos** [comment]
> @sopos do you want to cherry-pick [530caf6](https://github.com/beakerlib/beakerlib/commit/530caf62b206c268a37414b4ca41bd795de19c89) onto master? Probably a rebase error sneaked in [bc52b42](https://github.com/beakerlib/beakerlib/commit/bc52b426205949eae413136b38d719c333f91e9a)

good catch

**Review by psss — APPROVED** [review]
Looks good! Thanks. @sopos, I guess it's ready for merging?

**Pull request merged**
